---
- hosts: localhost
  connection: local
  roles:
    - role: indigo-dc.galaxycloud-refdata
      get_refdata: 'true'
      refdata_dir: '/refdata'
      refdata_repository_name: 'elixir-italy.galaxy.refdata'
      refdata_provider_type: 'cvmfs'
      refdata_cvmfs_server_url: '90.147.102.186'
      refdata_cvmfs_repository_name: 'elixir-italy.galaxy.refdata'
      refdata_cvmfs_key_file: 'elixir-italy.galaxy.refdata.pub'
      refdata_cvmfs_proxy_url: 'DIRECT'
  post_tasks:
    - stat: path=/var/log/galaxy/uwsgi.pid
      register: galaxy_pid
    - supervisorctl:
        name: '{{item}}'
        state: stopped
      with_items:
        - 'postgresql'
        - 'nginx'
        - 'proftpd'
        - 'galaxy:'
      when: galaxy_pid.stat.exists
